- name: Add Smominru CC IP Addresses to PANOS as Object Group
  hosts: panos_fw
  connection: local
  gather_facts: False

  roles:
    - role: paloaltonetworks.paloaltonetworks
  vars:
    objects_list: []

  tasks:
  - name: Grab variables from ansible-vault
    include_vars: 'variables.yml'
    no_log: 'yes'

  - name: Create objects
    panos_address_object:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      name: 'Smominru-{{ item }}'
      value: '{{ item }}'
      description: 'Botnet command controller'
      tag: ['botnet']
      commit: False
    with_items:
      - 70.39.124.66
      - 174.128.248.10
      - 174.128.244.18
      - 74.222.14.61
      - 78.142.29.152
      - 23.88.160.137
      - 139.5.177.19
      - 79.124.78.127
      - 74.222.14.94
      - 173.208.139.170
      - 173.208.172.202
      - 139.5.177.10
      - 45.58.135.106
      - 66.117.6.174
      - 223.25.247.240
      - 35.182.171.137
      - 54.255.141.50
      - 173.247.239.186
      - 192.187.111.66

  - name: create list with set_fact
    set_fact:
      objects_list: "{{ objects_list }} + [ 'Smominru-{{ item }}' ]"
    with_items:
      - 70.39.124.66
      - 174.128.248.10
      - 174.128.244.18
      - 74.222.14.61
      - 78.142.29.152
      - 23.88.160.137
      - 139.5.177.19
      - 79.124.78.127
      - 74.222.14.94
      - 173.208.139.170
      - 173.208.172.202
      - 139.5.177.10
      - 45.58.135.106
      - 66.117.6.174
      - 223.25.247.240
      - 35.182.171.137
      - 54.255.141.50
      - 173.247.239.186
      - 192.187.111.66

  - name: Create static address group
    panos_address_group:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      name: 'Smominru-CC-IP-Grp'
      static_value: '{{ objects_list }}'
      tag: ['botnet']
      commit: False

  - name: Commit pending firewall changes
    panos_commit:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
